#!/usr/bin/env node
'use strict';require('dotenv').config({path:require('path').join(__dirname,'../.env')});const{Sequelize}=require('sequelize');const seq=new Sequelize(process.env.DB_NAME,process.env.DB_USER,process.env.DB_PASS,{host:process.env.DB_HOST||'127.0.0.1',port:Number(process.env.DB_PORT||3306),dialect:'mysql',logging:false});
async function column(table,name,ddl){const c=await seq.getQueryInterface().describeTable(table);if(!c[name])await seq.query(`ALTER TABLE ${table} ADD COLUMN ${name} ${ddl}`)}async function run(){await seq.authenticate();
await seq.query("ALTER TABLE media MODIFY module ENUM('kids','discover','sports','play') NULL, MODIFY entity_type VARCHAR(64) NULL, MODIFY entity_id INT UNSIGNED NULL, MODIFY media_type ENUM('youtube','video','audio','pdf','image','coloring','zip','downloadable') NOT NULL");
for(const [n,d]of Object.entries({thumbnail_source:"ENUM('provider','custom','generated') NOT NULL DEFAULT 'provider'",thumbnail_quality:'VARCHAR(30) NULL',status:"ENUM('draft','published','broken','processing') NOT NULL DEFAULT 'published'",metadata:'JSON NULL',storage_bytes:'BIGINT UNSIGNED NOT NULL DEFAULT 0',checksum:'VARCHAR(64) NULL',sync_hash:'VARCHAR(64) NULL',last_synced_at:'DATETIME NULL',last_checked_at:'DATETIME NULL',broken_at:'DATETIME NULL',updated_by:'INT NULL',deleted_by:'INT NULL',deleted_at:'DATETIME NULL',purge_after:'DATETIME NULL'}))await column('media',n,d);
await seq.query('DROP INDEX uq_media_entity_provider_external ON media').catch(()=>{});await seq.query('CREATE FULLTEXT INDEX ft_media_search ON media(title,description,external_id)').catch(()=>{});
const ddls=[
`CREATE TABLE IF NOT EXISTS media_links(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,media_id INT UNSIGNED NOT NULL,module ENUM('kids','discover','sports','play') NOT NULL,entity_type VARCHAR(64) NOT NULL,entity_id INT UNSIGNED NOT NULL,sort_order INT NOT NULL DEFAULT 0,featured TINYINT(1) NOT NULL DEFAULT 0,visible TINYINT(1) NOT NULL DEFAULT 1,label VARCHAR(80),created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_media_link(media_id,module,entity_type,entity_id),KEY idx_media_link_entity(module,entity_type,entity_id,visible,sort_order),CONSTRAINT fk_media_link_media FOREIGN KEY(media_id) REFERENCES media(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
`CREATE TABLE IF NOT EXISTS media_collections(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,uuid CHAR(36) NOT NULL UNIQUE,name VARCHAR(191) NOT NULL,slug VARCHAR(191) NOT NULL UNIQUE,description TEXT,cover_url VARCHAR(1000),visible TINYINT(1) NOT NULL DEFAULT 1,created_by INT,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
`CREATE TABLE IF NOT EXISTS media_collection_items(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,collection_id INT UNSIGNED NOT NULL,media_id INT UNSIGNED NOT NULL,sort_order INT NOT NULL DEFAULT 0,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_collection_media(collection_id,media_id),CONSTRAINT fk_mci_collection FOREIGN KEY(collection_id) REFERENCES media_collections(id) ON DELETE CASCADE,CONSTRAINT fk_mci_media FOREIGN KEY(media_id) REFERENCES media(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
`CREATE TABLE IF NOT EXISTS media_tags(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100) NOT NULL UNIQUE,slug VARCHAR(100) NOT NULL UNIQUE,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
`CREATE TABLE IF NOT EXISTS media_tag_map(media_id INT UNSIGNED NOT NULL,tag_id INT UNSIGNED NOT NULL,PRIMARY KEY(media_id,tag_id),CONSTRAINT fk_mtm_media FOREIGN KEY(media_id) REFERENCES media(id) ON DELETE CASCADE,CONSTRAINT fk_mtm_tag FOREIGN KEY(tag_id) REFERENCES media_tags(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
`CREATE TABLE IF NOT EXISTS media_translations(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,media_id INT UNSIGNED NOT NULL,language VARCHAR(10) NOT NULL,title VARCHAR(191) NOT NULL,description TEXT,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_media_translation(media_id,language),CONSTRAINT fk_mt_media FOREIGN KEY(media_id) REFERENCES media(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
`CREATE TABLE IF NOT EXISTS media_versions(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,media_id INT UNSIGNED NOT NULL,version INT UNSIGNED NOT NULL,snapshot JSON NOT NULL,changes JSON,created_by INT,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_media_version(media_id,version),CONSTRAINT fk_mv_media FOREIGN KEY(media_id) REFERENCES media(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
`CREATE TABLE IF NOT EXISTS media_events(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,media_id INT UNSIGNED NOT NULL,event_type ENUM('view','click','download','play','progress','complete') NOT NULL,watch_seconds INT UNSIGNED,completion_rate DECIMAL(5,2),referrer VARCHAR(500),country CHAR(2),language VARCHAR(10),device VARCHAR(40),visitor_hash VARCHAR(64),created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,KEY idx_media_event(media_id,event_type,created_at),CONSTRAINT fk_me_media FOREIGN KEY(media_id) REFERENCES media(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`];for(const ddl of ddls)await seq.query(ddl);
await seq.query(`INSERT IGNORE INTO media_links(media_id,module,entity_type,entity_id,sort_order,featured,visible,created_at,updated_at) SELECT id,module,entity_type,entity_id,sort_order,featured,visible,created_at,updated_at FROM media WHERE module IS NOT NULL AND entity_type IS NOT NULL AND entity_id IS NOT NULL`);
await seq.query(`CREATE TEMPORARY TABLE media_dupes AS SELECT provider,external_id,MIN(id) keep_id FROM media WHERE external_id IS NOT NULL GROUP BY provider,external_id HAVING COUNT(*)>1`);await seq.query(`INSERT IGNORE INTO media_links(media_id,module,entity_type,entity_id,sort_order,featured,visible,created_at,updated_at) SELECT d.keep_id,l.module,l.entity_type,l.entity_id,l.sort_order,l.featured,l.visible,l.created_at,l.updated_at FROM media_links l JOIN media m ON m.id=l.media_id JOIN media_dupes d ON d.provider=m.provider AND d.external_id=m.external_id WHERE l.media_id<>d.keep_id`);await seq.query(`DELETE l FROM media_links l JOIN media m ON m.id=l.media_id JOIN media_dupes d ON d.provider=m.provider AND d.external_id=m.external_id WHERE l.media_id<>d.keep_id`);await seq.query(`DELETE m FROM media m JOIN media_dupes d ON d.provider=m.provider AND d.external_id=m.external_id WHERE m.id<>d.keep_id`);await seq.query('DROP TEMPORARY TABLE media_dupes');await seq.query('CREATE UNIQUE INDEX uq_media_provider_external ON media(provider,external_id)').catch(()=>{});console.log('Media Center Phase 2 migration complete');await seq.close()}run().catch(e=>{console.error(e);process.exit(1)});
