import React from 'react';
import {
  AlertTriangle,
  Award,
  Bike,
  Ban,
  Calculator,
  CalendarDays,
  Camera,
  CircleDot,
  Car,
  Check,
  ChefHat,
  ClipboardList,
  Clock,
  Coffee,
  Copy,
  Croissant,
  Heart,
  Home,
  Image,
  LocateFixed,
  Link as LinkIcon,
  Map,
  MapPin,
  Mail,
  Maximize2,
  MessageCircle,
  Moon,
  Navigation,
  Package,
  Pause,
  Phone,
  Play,
  Pill,
  Search,
  Settings2,
  Share2,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Sparkles,
  Star,
  Store,
  Sun,
  Trash2,
  User,
  Utensils,
  Bell,
  BookOpen,
  Building2,
  CreditCard,
  Database,
  Download,
  Edit3,
  Eye,
  FileText,
  Flame,
  FolderOpen,
  Gift,
  Gem,
  Globe2,
  Inbox,
  Info,
  Keyboard,
  Monitor,
  Printer,
  RadioTower,
  ReceiptText,
  RefreshCw,
  Rocket,
  Save,
  ScanLine,
  Shuffle,
  Table2,
  Tags,
  Target,
  Thermometer,
  Ticket,
  TrendingDown,
  TrendingUp,
  Upload,
  Truck,
  Users,
  Wallet,
  Plus,
  Landmark,
  Cpu,
  X,
} from 'lucide-react';

const ICONS = {
  alert: AlertTriangle,
  award: Award,
  bakery: Croissant,
  cafe: Coffee,
  calculator: Calculator,
  calendar: CalendarDays,
  camera: Camera,
  cart: ShoppingCart,
  car: Car,
  check: Check,
  chef: ChefHat,
  clock: Clock,
  clipboard: ClipboardList,
  close: X,
  copy: Copy,
  delivery: Bike,
  directions: Navigation,
  heart: Heart,
  home: Home,
  locate: LocateFixed,
  map: Map,
  mapPin: MapPin,
  message: MessageCircle,
  medicine: Pill,
  moon: Moon,
  package: Package,
  pause: Pause,
  phone: Phone,
  play: Play,
  search: Search,
  settings: Settings2,
  share: Share2,
  shield: ShieldCheck,
  shopping: ShoppingBag,
  sparkles: Sparkles,
  star: Star,
  store: Store,
  sun: Sun,
  trash: Trash2,
  user: User,
  utensils: Utensils,
  bank: Landmark,
  bell: Bell,
  bike: Bike,
  book: BookOpen,
  card: CreditCard,
  chart: TrendingUp,
  cpu: Cpu,
  database: Database,
  download: Download,
  edit: Edit3,
  eye: Eye,
  fileText: FileText,
  gift: Gift,
  globe: Globe2,
  history: ReceiptText,
  image: Image,
  inbox: Inbox,
  info: Info,
  lock: ShieldCheck,
  monitor: Monitor,
  plus: Plus,
  printer: Printer,
  receipt: ReceiptText,
  refresh: RefreshCw,
  save: Save,
  shuffle: Shuffle,
  table: Table2,
  target: Target,
  thermometer: Thermometer,
  ticket: Ticket,
  trendingDown: TrendingDown,
  trendingUp: TrendingUp,
  truck: Truck,
  users: Users,
  wallet: Wallet,
  note: FileText,
  ban: Ban,
  building: Building2,
  circle: CircleDot,
  flame: Flame,
  folder: FolderOpen,
  gem: Gem,
  keyboard: Keyboard,
  link: LinkIcon,
  mail: Mail,
  radio: RadioTower,
  rocket: Rocket,
  scan: ScanLine,
  tags: Tags,
  upload: Upload,
  lightbulb: Info,
  whatsapp: MessageCircle,
};

export function PremiumIcon({ name, size = 16, strokeWidth = 2.2, className = '', style, title }) {
  const Icon = ICONS[name] || Store;
  return <Icon aria-hidden={title ? undefined : true} aria-label={title} size={size} strokeWidth={strokeWidth} className={className} style={style} />;
}

export function PremiumIconBadge({ name, size = 18, className = '', style }) {
  return (
    <span className={'premium-icon-badge' + (className ? ' ' + className : '')} style={style} aria-hidden="true">
      <PremiumIcon name={name} size={size} />
    </span>
  );
}

export default PremiumIcon;
