'use strict';
const assert=require('assert');const fs=require('fs');const os=require('os');const path=require('path');const AdmZip=require('adm-zip');
const {ManifestValidator}=require('../src/modules/comics/importer/ManifestValidator');const {VersionManager}=require('../src/modules/comics/importer/VersionManager');const PackageExtractor=require('../src/modules/comics/importer/PackageExtractor');const PageImporter=require('../src/modules/comics/importer/PageImporter');const AssetImporter=require('../src/modules/comics/importer/AssetImporter');const SeriesResolver=require('../src/modules/comics/importer/SeriesResolver');const EpisodeResolver=require('../src/modules/comics/importer/EpisodeResolver');
const manifest={packageType:'ifilino-comic',packageVersion:2,seriesId:'ibn-battuta',seriesTitle:'ابن بطوطة',seasonNumber:1,episodeId:'ibn-battuta-002',episodeNumber:2,episodeTitle:'الطريق إلى تلمسان',episodeVersion:4,publicationOrder:2,language:'ar',generatedAt:'2026-08-05T11:30:00Z'};
const tests=[];const test=(name,fn)=>tests.push([name,fn]);const rejects=(fn,text)=>assert.throws(fn,e=>e.message.includes(text));
test('new series manifest is metadata-driven',()=>{const m=ManifestValidator.validate(manifest);assert.equal(m.seriesId,'ibn-battuta');assert.equal(m.episodeId,'ibn-battuta-002')});
test('new episode defaults publication order safely',()=>{const m=ManifestValidator.validate({...manifest,publicationOrder:undefined});assert.equal(m.publicationOrder,2)});
test('existing episode update accepts newer version',()=>assert.equal(VersionManager.action(3,4),'update'));
test('older version rejection',()=>rejects(()=>VersionManager.action(4,2),'older'));
test('duplicate episode rejection',()=>rejects(()=>VersionManager.action(4,4),'already exists'));
test('invalid manifest reports required fields',()=>rejects(()=>ManifestValidator.validate({packageType:'ifilino-comic',packageVersion:2}),'Missing seriesId'));
test('invalid packageVersion is rejected',()=>rejects(()=>ManifestValidator.validate({...manifest,packageVersion:99}),'Unsupported'));
test('missing manifest aborts extraction',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'comic-test-')),file=path.join(dir,'x.zip'),zip=new AdmZip();zip.addFile('page-001.png',Buffer.from('x'));zip.writeZip(file);rejects(()=>PackageExtractor.inspect(file),'Missing manifest');fs.rmSync(dir,{recursive:true,force:true})});
test('missing page reference is rejected',()=>rejects(()=>PageImporter.entries([],{pages:['pages/page-001.png']}),'Page missing'));
test('missing asset reference is rejected',()=>rejects(()=>AssetImporter.copy([],['assets/font.woff2'],os.tmpdir()),'Asset missing'));
test('series resolver uses immutable series_uid',async()=>{let sql='';const db={query:async q=>{sql=q;return[]}};await SeriesResolver.find(db,'ibn-battuta');assert(sql.includes('series_uid=:uid'))});
test('episode resolver uses immutable episode_uid',async()=>{let sql='';const db={query:async q=>{sql=q;return[]}};await EpisodeResolver.find(db,'ibn-battuta-002');assert(sql.includes('episode_uid=:uid'))});
test('rollback path can be invoked on failure',async()=>{let rolled=false;const tx={rollback:async()=>{rolled=true}};try{throw new Error('Asset missing')}catch{await tx.rollback()}assert(rolled)});
(async()=>{for(const[name,fn]of tests){await fn();console.log('✓',name)}console.log(`${tests.length} Comics importer v2 tests passed.`)})().catch(e=>{console.error(e);process.exit(1)});