import React,{useCallback,useEffect,useRef,useState}from"react";
import{motion,useReducedMotion}from"framer-motion";
import{Archive,CheckCircle2,Download,FileArchive,History,LoaderCircle,ShieldCheck,Trash2,UploadCloud,XCircle}from"lucide-react";
import{io}from"socket.io-client";
import{useAuth}from"../auth/AuthContext";
import{aiImportService}from"./aiImportService";
import type{ImportHistory as HistoryEntry,ImportRecord}from"./types";
import"bootstrap/dist/css/bootstrap.min.css";
import"./ai-package-import.css";

const stages=["Uploading","Extracting","Validating","Publishing","Cleaning"]as const;
export default function AIPackageImportPage(){
 const{token}=useAuth() as unknown as {token:string|undefined};const reduced=useReducedMotion();const input=useRef<HTMLInputElement>(null);const[drag,setDrag]=useState(false),[uploading,setUploading]=useState(false),[localProgress,setLocalProgress]=useState(0),[imports,setImports]=useState<ImportRecord[]>([]),[history,setHistory]=useState<HistoryEntry[]>([]),[error,setError]=useState("");
 const refresh=useCallback(async()=>{if(!token)return;try{const[next,h]=await Promise.all([aiImportService.list(token),aiImportService.history(token)]);setImports(next);setHistory(h);}catch(reason){setError(reason instanceof Error?reason.message:String(reason));}},[token]);
 useEffect(()=>{void refresh();const timer=window.setInterval(()=>void refresh(),2000);if(!token)return()=>window.clearInterval(timer);const socket=io(window.location.origin,{path:"/api/socket.io",transports:["websocket","polling"]});socket.on("connect",()=>socket.emit("superadmin:join",token));for(const event of["import-created","upload-progress","extract-progress","validation-progress","publish-progress","cleanup-progress","import-success","import-failed"])socket.on(event,()=>void refresh());return()=>{window.clearInterval(timer);socket.disconnect();};},[refresh,token]);
 const submit=async(file?:File)=>{if(!file||!token)return;if(!file.name.toLowerCase().endsWith(".zip")){setError("Sélectionnez uniquement un package ZIP.");return;}setError("");setUploading(true);setLocalProgress(0);try{await aiImportService.upload(file,token,setLocalProgress);await refresh();}catch(reason){setError(reason instanceof Error?reason.message:String(reason));}finally{setUploading(false);if(input.current)input.current.value="";}};
 return <div className="aip-import-page">
  <nav aria-label="Fil d’Ariane"><ol className="breadcrumb"><li className="breadcrumb-item">SuperAdmin</li><li className="breadcrumb-item">AI Publisher</li><li className="breadcrumb-item active">Imports</li></ol></nav>
  <header className="aip-header"><div><span className="aip-kicker">AI Package Import</span><h1>Publier un package, sans terminal.</h1><p>Déposez le ZIP généré par votre projet ChatGPT. Validation, publication et nettoyage sont automatisés.</p></div><div className="aip-trust"><ShieldCheck/><span><strong>Pipeline sécurisé</strong><small>ZIP supprimé après traitement</small></span></div></header>
  {error&&<div className="alert alert-danger d-flex align-items-center gap-2" role="alert"><XCircle size={20}/><span>{error}</span><button className="btn-close ms-auto" aria-label="Fermer" onClick={()=>setError("")}/></div>}
  <motion.section initial={reduced?false:{opacity:0,y:8}} animate={{opacity:1,y:0}} className={`aip-dropzone${drag?" is-dragging":""}`} onDragEnter={event=>{event.preventDefault();setDrag(true)}} onDragOver={event=>event.preventDefault()} onDragLeave={()=>setDrag(false)} onDrop={event=>{event.preventDefault();setDrag(false);void submit(event.dataTransfer.files[0])}}>
   <div className="aip-upload-icon">{uploading?<LoaderCircle className="aip-spin"/>:<UploadCloud/>}</div><h2>{uploading?"Upload en cours…":"Déposez votre package ZIP ici"}</h2><p>Un seul fichier `.zip`, 50 Mio maximum. Les fichiers doivent être placés à la racine.</p><input ref={input} className="visually-hidden" id="ai-package-file" type="file" accept=".zip,application/zip" onChange={event=>void submit(event.target.files?.[0])}/><button className="btn btn-primary btn-lg" disabled={uploading} onClick={()=>input.current?.click()}><FileArchive size={19}/> Choisir un package</button>
   {uploading&&<div className="aip-local-progress"><div className="progress" role="progressbar" aria-valuenow={localProgress} aria-valuemin={0} aria-valuemax={100}><div className="progress-bar" style={{width:`${localProgress}%`}}/></div><strong>{localProgress}%</strong></div>}
  </motion.section>
  <section className="aip-section"><div className="aip-section-title"><div><span className="aip-kicker">Temps réel</span><h2>File d’import</h2></div><span className="badge text-bg-dark">{imports.filter(item=>!["Completed","Failed"].includes(item.status)).length} actif(s)</span></div>
   {imports.length===0?<div className="aip-empty"><Archive/><h3>Aucun import</h3><p>Votre prochain package apparaîtra ici.</p></div>:<div className="aip-import-list">{imports.map(item=><article className="aip-import-card" key={item.id}><div className="aip-file-icon"><FileArchive/></div><div className="aip-import-main"><div className="aip-import-heading"><div><h3>{item.title||item.filename}</h3><span>{item.module||"Module en détection"} · {item.filename}</span></div><span className={`aip-status aip-status--${item.status.toLowerCase()}`}>{item.status==="Completed"?<CheckCircle2/>:item.status==="Failed"?<XCircle/>:<LoaderCircle className="aip-spin"/>}{item.status}</span></div><div className="progress" role="progressbar" aria-label={`Progression ${item.filename}`} aria-valuenow={item.progress} aria-valuemin={0} aria-valuemax={100}><div className={`progress-bar${item.status==="Failed"?" bg-danger":""}`} style={{width:`${item.progress}%`}}/></div><div className="aip-steps">{stages.map((stage,index)=>{const current=stages.indexOf(item.status as typeof stages[number]),done=item.status==="Completed"||current>index;return <span className={done?"done":item.status===stage?"active":""} key={stage}>{done?<CheckCircle2/>:<span>{index+1}</span>}{stage}</span>})}</div>{item.errors.length>0&&<div className="aip-errors" role="alert"><strong>Validation interrompue</strong>{item.errors.map(message=><p key={message}>{message}</p>)}<button className="btn btn-outline-danger btn-sm" type="button" onClick={()=>void aiImportService.downloadReport(item.id,token!)}><Download size={16}/> Télécharger le rapport d’erreur</button></div>}</div></article>)}</div>}
  </section>
  <section className="aip-section"><div className="aip-section-title"><div><span className="aip-kicker">Traçabilité</span><h2>Historique</h2></div><button className="btn btn-outline-danger" disabled={!history.length} onClick={async()=>{if(token&&window.confirm("Supprimer tout l’historique d’import ?")){await aiImportService.clearHistory(token);await refresh();}}}><Trash2 size={17}/> Supprimer l’historique</button></div>
   <div className="table-responsive aip-table-wrap"><table className="table align-middle mb-0"><thead><tr><th>Date</th><th>Package</th><th>Module</th><th>Titre</th><th>Durée</th><th>Résultat</th></tr></thead><tbody>{history.map((item,index)=><tr key={`${item.filename}-${index}`}><td>{new Date(item.date).toLocaleString("fr")}</td><td>{item.filename}</td><td>{item.module}</td><td>{item.title}</td><td>{(item.duration/1000).toFixed(1)} s</td><td><span className={`badge ${item.result==="Completed"?"text-bg-success":"text-bg-danger"}`}>{item.result}</span></td></tr>)}</tbody></table>{!history.length&&<div className="aip-empty aip-empty--small"><History/><p>Aucun historique disponible.</p></div>}</div>
  </section>
 </div>;
}
