import React, { useMemo, useState } from 'react';
import { Activity, Archive, Bot, CalendarClock, CheckCircle2, Clock3, Cpu, FileCheck2, FileImage, FileText, Gauge, Globe2, Layers3, Pause, Play, Plug, RefreshCw, Search, Settings2, Tags, TerminalSquare, Video } from 'lucide-react';
import { activities, editors, health, jobs, monthlySeries, providers, publications, weeklySeries, workflows } from '../data/mockData';
import { AIStatusCard, HealthCard, JobCard, MetricCard, ModelCard, PromptCard, ProviderCard, PublicationCard, QueueCard, TemplateCard, TimelineCard, WorkflowCard } from '../components/Cards';
import { AuditViewer, LogViewer, QuickActions, RecentActivityCard, SystemStatus } from '../components/Widgets';
import { KanbanBoard, StatisticsChart, TimelineCalendar } from '../components/Operations';

function PageHeader({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: React.ReactNode }) {
  return <header className="ai-page-header"><div><p className="ai-eyebrow">{eyebrow}</p><h1>{title}</h1><p>{description}</p></div>{action}</header>;
}

export function DashboardPage({ onNewJob }: { onNewJob: () => void }) {
  return <><PageHeader eyebrow="Cockpit éditorial" title="Bonjour, Nadia." description="Voici ce qui se passe dans votre rédaction IA aujourd’hui." action={<QuickActions onNewJob={onNewJob} />} /><AIStatusCard /><section className="ai-metrics-grid"><MetricCard label="Articles générés" value="1 386" detail="+124 cette semaine" icon={FileText} trend="+9,8%" /><MetricCard label="Jobs actifs" value="07" detail="sur 12 workers" icon={Activity} /><MetricCard label="File d’attente" value="18" detail="~ 14 min" icon={Layers3} /><MetricCard label="Taux de réussite" value="97,4%" detail="30 derniers jours" icon={CheckCircle2} trend="+1,2%" /><MetricCard label="Temps moyen" value="2m 18s" detail="-18 s ce mois" icon={Clock3} /><MetricCard label="Providers actifs" value="04" detail="1 dégradé" icon={Cpu} /></section><section className="ai-dashboard-grid"><StatisticsChart title="Publications cette semaine" data={weeklySeries} labels={['L', 'M', 'M', 'J', 'V', 'S', 'D']} /><RecentActivityCard activities={activities} /></section><section className="ai-content-grid ai-content-grid--3"><QueueCard count={4} wait="3 min" priority="critique" /><QueueCard count={6} wait="8 min" priority="haute" /><QueueCard count={8} wait="14 min" priority="normale" /></section><section className="ai-section-block"><div className="ai-section-head"><div><p className="ai-eyebrow">Production</p><h2>Jobs en cours</h2></div><SystemStatus /></div><div className="ai-content-grid ai-content-grid--3">{jobs.slice(0, 3).map((job) => <JobCard key={job.id} job={job} />)}</div></section></>;
}

export function JobsPage() {
  const [query, setQuery] = useState('');
  const filtered = jobs.filter((job) => `${job.title} ${job.id} ${job.editor}`.toLowerCase().includes(query.toLowerCase()));
  return <><PageHeader eyebrow="Production" title="Jobs IA" description="Pilotez chaque génération, de la validation à l’archivage." action={<button className="ai-btn ai-btn--primary"><Play size={17} /> Démarrer la sélection</button>} /><div className="ai-toolbar"><label className="ai-inline-search"><Search /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Filtrer les jobs…" /></label><select className="ai-select" aria-label="Filtrer par statut"><option>Tous les statuts</option><option>En cours</option><option>Échec</option></select><button className="ai-btn ai-btn--ghost"><RefreshCw /> Actualiser</button></div><div className="ai-table-wrap"><table className="ai-table"><thead><tr><th>Job</th><th>Éditeur</th><th>Statut</th><th>Priorité</th><th>Progression</th><th>Modèle</th><th>Actions</th></tr></thead><tbody>{filtered.map((job) => <tr key={job.id}><td><strong>{job.title}</strong><small>{job.id}</small></td><td>{job.editor}</td><td><span className={`ai-text-status ai-text-status--${job.status}`}>{job.status}</span></td><td>{job.priority}</td><td><div className="ai-progress"><span style={{ width: `${job.progress}%` }} /></div><small>{job.progress}%</small></td><td>{job.model}</td><td><div className="ai-row-actions"><button aria-label="Mettre en pause"><Pause /></button><button aria-label="Relancer"><RefreshCw /></button><button aria-label="Archiver"><Archive /></button></div></td></tr>)}</tbody></table></div></>;
}

export function QueuePage() { return <><PageHeader eyebrow="Orchestration" title="File d’attente" description="Réordonnez les priorités par glisser-déposer ou avec le sélecteur clavier." /><KanbanBoard initialJobs={jobs} /></>; }
export function PlanningPage() { return <><PageHeader eyebrow="Calendrier" title="Planning éditorial" description="Visualisez la charge et les créneaux de publication." /><TimelineCalendar jobs={jobs} /></>; }

export function EditorsPage() { return <><PageHeader eyebrow="Rédaction" title="Éditeurs IA" description="Une vision commune de Discover, Sports, Kids, Stories et GamingHub." /><div className="ai-content-grid ai-content-grid--3">{editors.map((editor) => <article className="ai-card ai-editor-card" key={editor.id}><div className={`ai-editor-mark ai-editor-mark--${editor.id}`}><Bot /></div><div className="ai-card-head"><h2>{editor.name}</h2><span className={`ai-badge ai-badge--${editor.status === 'active' ? 'success' : 'warning'}`}><span />{editor.status}</span></div><p>{editor.description}</p><dl><div><dt>Articles</dt><dd>{editor.articles}</dd></div><div><dt>Réussite</dt><dd>{editor.successRate}%</dd></div><div><dt>Cadence</dt><dd>{editor.cadence}</dd></div></dl><div className="ai-card-actions"><button className="ai-btn ai-btn--ghost">Configurer</button><button className="ai-btn ai-btn--ghost">Historique</button></div></article>)}</div></>; }
export function ProvidersPage() { return <><PageHeader eyebrow="Intelligence" title="Providers" description="Disponibilité, latence et consommation des fournisseurs de modèles." /><div className="ai-content-grid ai-content-grid--2">{providers.map((provider) => <ProviderCard provider={provider} key={provider.id} />)}</div></>; }
export function ModelsPage() { return <><PageHeader eyebrow="Intelligence" title="Modèles" description="Catalogue des modèles autorisés par la rédaction." /><div className="ai-content-grid ai-content-grid--3"><ModelCard name="GPT-5" provider="OpenAI" context="256K" cost="0,018 € / 1K" /><ModelCard name="Claude Sonnet" provider="Anthropic" context="200K" cost="0,015 € / 1K" /><ModelCard name="Gemini Pro" provider="Google AI" context="1M" cost="0,012 € / 1K" /><ModelCard name="Mistral Large" provider="Mistral AI" context="128K" cost="0,009 € / 1K" /></div></>; }
export function WorkflowsPage() { return <><PageHeader eyebrow="Automatisation" title="Workflows" description="Séquences éditoriales configurables, versionnées et observables." /><div className="ai-content-grid ai-content-grid--3">{workflows.map((workflow) => <WorkflowCard workflow={workflow} key={workflow.id} />)}</div></>; }

export function SchedulerPage() { return <><PageHeader eyebrow="Automatisation" title="Scheduler" description="Récurrences, fenêtres de production et règles d’exécution." action={<button className="ai-btn ai-btn--primary"><CalendarClock /> Nouvelle règle</button>} /><div className="ai-timeline">{[
  ['06:00', 'Brief quotidien Discover', 'Tous les jours · Europe/Paris'],
  ['08:30', 'Flash Sports', 'Lun–Ven · toutes les 90 min'],
  ['14:00', 'Kids après l’école', 'Mer, Sam et Dim'],
  ['18:30', 'GamingHub Daily', 'Tous les jours']
].map(([time, title, detail]) => <TimelineCard key={title} time={time} title={title} detail={detail} />)}</div></>; }

export function PublicationsPage() { return <><PageHeader eyebrow="Bibliothèque" title="Publications" description="Packages prêts, en révision ou publiés." /><div className="ai-content-grid ai-content-grid--2">{publications.map((publication) => <PublicationCard key={publication.id} publication={publication} />)}</div></>; }
export function ImagesPage() { return <><PageHeader eyebrow="Assets" title="Images" description="Contrôle des visuels générés, couvertures et formats." /><div className="ai-asset-grid">{publications.map((publication, index) => <article className="ai-card ai-asset-card" key={publication.id}><div className={`ai-asset-placeholder ai-asset-placeholder--${index}`}><FileImage /></div><h3>{publication.title}</h3><p>cover.webp · 1600 × 900</p><div className="ai-card-foot"><span>Alt validé</span><strong>{92 + index}%</strong></div></article>)}</div></>; }
export function VideosPage() { return <><PageHeader eyebrow="Assets" title="Vidéos" description="Espace préparé pour les rendus courts et formats sociaux." /><div className="ai-card ai-feature-banner"><Video /><div><p className="ai-eyebrow">Pipeline vidéo</p><h2>3 rendus en préparation</h2><p>Les previews et transcodages restent simulés dans cette version.</p></div><button className="ai-btn ai-btn--primary">Voir la file</button></div></>; }

export function SeoPage() { return <><PageHeader eyebrow="Qualité éditoriale" title="SEO" description="Scores, longueur des métadonnées et couverture des champs sociaux." /><section className="ai-metrics-grid"><MetricCard label="Score moyen" value="92/100" detail="+4 ce mois" icon={Gauge} /><MetricCard label="Canonical" value="100%" detail="1 386 articles" icon={Globe2} /><MetricCard label="Descriptions" value="98,6%" detail="19 à revoir" icon={FileCheck2} /><MetricCard label="Tags uniques" value="642" detail="12 fusionnés" icon={Tags} /></section><div className="ai-card"><div className="ai-section-head"><h2>Contrôles récents</h2><button className="ai-btn ai-btn--ghost">Exporter</button></div><div className="ai-seo-list">{publications.map((publication) => <div key={publication.id}><strong>{publication.title}</strong><span>{publication.editor}</span><div className="ai-progress"><span style={{ width: `${publication.score}%` }} /></div><b>{publication.score}</b></div>)}</div></div></>; }
export function AnalyticsPage() { return <><PageHeader eyebrow="Pilotage" title="Analytics" description="Tendances de production et performance éditoriale." /><StatisticsChart title="Publications mensuelles" data={monthlySeries} labels={['A', 'S', 'O', 'N', 'D', 'J', 'F', 'M', 'A', 'M', 'J', 'J']} /><section className="ai-content-grid ai-content-grid--3"><MetricCard label="Volume annuel" value="8 924" detail="contenus produits" icon={FileText} /><MetricCard label="Retries" value="2,1%" detail="-0,7 point" icon={RefreshCw} /><MetricCard label="Temps économisé" value="1 840 h" detail="estimation" icon={Clock3} /></section></>; }
export function TemplatesPage() { return <><PageHeader eyebrow="Bibliothèque" title="Templates" description="Structures réutilisables pour chaque ligne éditoriale." /><div className="ai-content-grid ai-content-grid--3"><TemplateCard title="Article découverte" format="Markdown" usage={342} /><TemplateCard title="Match report" format="Markdown" usage={218} /><TemplateCard title="Explique-moi Kids" format="Markdown" usage={164} /><TemplateCard title="Guide Gaming" format="Markdown" usage={196} /></div></>; }
export function PromptsPage() { return <><PageHeader eyebrow="Bibliothèque" title="Prompts" description="Instructions versionnées et contrôlées par la rédaction." /><div className="ai-content-grid ai-content-grid--2"><PromptCard title="Rédacteur scientifique" category="Discover" tokens={1840} /><PromptCard title="Analyse avant-match" category="Sports" tokens={1220} /><PromptCard title="Vulgarisation 8–12 ans" category="Kids" tokens={1560} /><PromptCard title="Narration immersive" category="Stories" tokens={2080} /></div></>; }
export function LogsPage() { return <><PageHeader eyebrow="Observabilité" title="Logs" description="Flux technique simulé des moteurs IA." action={<button className="ai-btn ai-btn--ghost"><TerminalSquare /> Pause stream</button>} /><LogViewer /></>; }
export function AuditPage() { return <><PageHeader eyebrow="Gouvernance" title="Audit" description="Traçabilité des actions humaines et automatiques." /><AuditViewer /></>; }
export function HealthPage() { return <><PageHeader eyebrow="Observabilité" title="Santé système" description="État des briques du pipeline de publication." /><div className="ai-content-grid ai-content-grid--3">{health.map((item) => <HealthCard item={item} key={item.id} />)}</div></>; }

export function SettingsPage() {
  const [saved, setSaved] = useState(false);
  return <><PageHeader eyebrow="Configuration" title="Paramètres" description="Préférences globales du cockpit. Les changements restent locaux." /><form className="ai-card ai-settings-form" onSubmit={(event) => { event.preventDefault(); setSaved(true); }}><fieldset><legend>Production</legend><label>Jobs simultanés<input type="number" defaultValue={12} min={1} max={50} /></label><label>Fuseau horaire<select defaultValue="Europe/Paris"><option>Europe/Paris</option><option>Africa/Algiers</option><option>UTC</option></select></label></fieldset><fieldset><legend>Validation</legend><label className="ai-switch-row"><span><strong>Validation humaine</strong><small>Exiger une revue avant publication</small></span><input type="checkbox" defaultChecked /></label><label className="ai-switch-row"><span><strong>Retry automatique</strong><small>Relancer les erreurs récupérables</small></span><input type="checkbox" defaultChecked /></label></fieldset><button className="ai-btn ai-btn--primary"><Settings2 /> Enregistrer</button>{saved && <p className="ai-success-message" role="status">Préférences enregistrées localement.</p>}</form></>;
}

export function PluginsPage() {
  const plugins = useMemo(() => [['Slack notifications', 'Alertes éditoriales', true], ['Discord newsroom', 'Suivi des publications', false], ['Email digest', 'Résumé quotidien', true], ['Webhook personnalisé', 'Automatisation externe', false]] as const, []);
  return <><PageHeader eyebrow="Extensions" title="Plugins" description="Hooks prêts pour les futures intégrations, sans appel externe." /><div className="ai-content-grid ai-content-grid--2">{plugins.map(([name, detail, enabled]) => <article className="ai-card ai-plugin-card" key={name}><div className="ai-icon-box"><Plug /></div><div><h3>{name}</h3><p>{detail}</p></div><span className={`ai-badge ai-badge--${enabled ? 'success' : 'info'}`}><span />{enabled ? 'activé' : 'disponible'}</span><button className="ai-btn ai-btn--ghost">{enabled ? 'Configurer' : 'Activer'}</button></article>)}</div></>;
}
