'use strict';
const crypto=require('crypto');const{Media,MediaLink,MediaTranslation,MediaVersion,PortalContent,Article,PlayGame}=require('../../../models');const youtube=require('./providers/youtubeProvider');const{providers:urlProviders}=require('./providers/urlProviders');const providers=new Map([[youtube.name,youtube],...urlProviders.map(p=>[p.name,p])]),cache=new Map(),TTL=21600000;
function providerFor(input){const p=providers.get(input.provider||(input.media_type==='youtube'?'youtube':null));if(!p)throw Object.assign(new Error('Unsupported media provider'),{status:422});return p}function hash(v){return crypto.createHash('sha256').update(JSON.stringify(v)).digest('hex')}
async function enrich(input,{fresh=false,preferProvider=false}={}){const p=providerFor(input),external_id=p.extractId(input.url),key=`${p.name}:${external_id}`,hit=cache.get(key);let data;if(!fresh&&hit&&hit.expires>Date.now())data=hit.value;else{data=await p.metadata(input.url);cache.set(key,{value:data,expires:Date.now()+TTL})}return{...data,...input,provider:p.name,media_type:input.media_type||data.media_type,external_id,url:data.url,title:preferProvider?(data.title||input.title):(input.title?.trim()||data.title),description:preferProvider?(data.description??input.description):(input.description??data.description),thumbnail:preferProvider?(data.thumbnail||input.thumbnail):(input.thumbnail||data.thumbnail),sync_hash:hash(data),last_synced_at:new Date(),last_checked_at:new Date()}}
async function assertEntity(x){let found=false;if(['kids','sports'].includes(x.module))found=!!await PortalContent.findOne({where:{id:x.entity_id,portal:x.module,content_type:x.entity_type},attributes:['id']});else if(x.module==='discover')found=!!await Article.findByPk(x.entity_id,{attributes:['id']});else if(x.module==='play')found=!!await PlayGame.findByPk(x.entity_id,{attributes:['id']});if(!found)throw Object.assign(new Error('Linked content does not exist'),{status:422})}
async function link(mediaId,relation){if(!relation?.module)return null;await assertEntity(relation);const[record]=await MediaLink.findOrCreate({where:{media_id:mediaId,module:relation.module,entity_type:relation.entity_type,entity_id:relation.entity_id},defaults:{sort_order:relation.sort_order||0,featured:!!relation.featured,visible:relation.visible!==false,label:relation.label||null}});return record}
async function create(input,userId){const v=await enrich(input);let media=await Media.findOne({where:{provider:v.provider,external_id:v.external_id},paranoid:false});if(media?.deleted_at)await media.restore();if(!media)media=await Media.create({...v,created_by:userId||null});await link(media.id,input);return media}
async function version(media,userId,changes){const last=await MediaVersion.max('version',{where:{media_id:media.id}})||0;return MediaVersion.create({media_id:media.id,version:last+1,snapshot:media.toJSON(),changes,created_by:userId||null})}
async function update(media,patch,userId){await version(media,userId,patch);const values=patch.url?await enrich({...media.toJSON(),...patch},{fresh:true}):patch;await media.update({...values,updated_by:userId||null});return media}
async function localize(media,language){const translations=media.translations||await MediaTranslation.findAll({where:{media_id:media.id}});const tr=translations.find(x=>x.language===language)||translations.find(x=>x.language==='en')||translations.find(x=>x.language==='fr')||translations[0];return{...media.toJSON(),title:tr?.title||media.title,description:tr?.description??media.description}}
module.exports={providers,enrich,assertEntity,link,create,version,update,localize,hash};
