import React from 'react';
import { ArrowRight, BadgeCheck, BookOpen, Check, ChevronDown, Crown, Download, FlaskConical, Headphones, Heart, Leaf, LockKeyhole, Rocket, ShieldCheck, Sparkles, Star, UsersRound, X } from 'lucide-react';
import { Link } from 'react-router-dom';
import { PortalBrand } from '../../modules/portals/components/PortalBrand';
import { PortalFooter } from '../../modules/portals/components/PortalFooter';
import SeoHead, { kidsAlternates } from '../../shared/seo/SeoHead';
import { useKidsRouteLanguage } from './useKidsRouteLanguage';
import { useSubscription } from '../../modules/subscriptions';
import './kids-premium-page.css';

const COPY = {
  fr: { nav:'Premium', login:'Se connecter', eyebrow:'Le meilleur d’iFilino Kids', title:'Des histoires qui donnent envie d’apprendre.', intro:'Une bibliothèque sûre et joyeuse pour lire, écouter et explorer à son rythme.', cta:"S'abonner", secondary:'Découvrir les avantages', trusted:'Pensé pour les enfants, approuvé par les parents', benefitsTitle:'Tout un monde à débloquer', benefits:[['Histoires sans limite','Des récits illustrés pour nourrir l’imagination.'],['Apprendre en explorant','Science, nature, espace et technologie en douceur.'],['Écouter partout','Des versions audio pour accompagner chaque moment.'],['Ressources à garder','Activités et supports éducatifs à télécharger.']], planTitle:'Simple pour toute la famille', planName:'iFilino Kids Premium', monthly:'par mois', planNote:'Annulable à tout moment. Accès familial inclus.', included:['Toute la bibliothèque Premium','Stories, Learn, Science, Nature, Space et Technology','Audio et ressources téléchargeables','Nouveautés ajoutées régulièrement'], finalTitle:'La prochaine aventure commence ici.', finalText:'Débloque aujourd’hui un espace sûr où la curiosité grandit chaque jour.' },
  en: { nav:'Premium', login:'Sign in', eyebrow:'The best of iFilino Kids', title:'Stories that inspire a love of learning.', intro:'A safe and joyful library for reading, listening and exploring at every child’s pace.', cta:'Subscribe', secondary:'Explore the benefits', trusted:'Made for kids, parent approved', benefitsTitle:'A whole world to unlock', benefits:[['Unlimited stories','Illustrated tales that grow imagination.'],['Learn by exploring','Science, nature, space and technology made friendly.'],['Listen anywhere','Audio versions for every part of the day.'],['Resources to keep','Downloadable activities and learning materials.']], planTitle:'Simple for the whole family', planName:'iFilino Kids Premium', monthly:'per month', planNote:'Cancel anytime. Family access included.', included:['The complete Premium library','Stories, Learn, Science, Nature, Space and Technology','Audio and downloadable resources','Fresh content added regularly'], finalTitle:'The next adventure starts here.', finalText:'Unlock a safe place where curiosity grows every day.' },
  ar: { nav:'Premium', login:'تسجيل الدخول', eyebrow:'أفضل ما في iFilino Kids', title:'قصص تجعل التعلّم مغامرة ممتعة.', intro:'مكتبة آمنة ومبهجة للقراءة والاستماع والاستكشاف حسب وتيرة كل طفل.', cta:'اشترك الآن', secondary:'اكتشف المزايا', trusted:'مصمم للأطفال ومعتمد من الآباء', benefitsTitle:'عالم كامل بانتظارك', benefits:[['قصص بلا حدود','حكايات مصورة تنمّي الخيال.'],['التعلم بالاستكشاف','العلوم والطبيعة والفضاء والتكنولوجيا ببساطة.'],['استمع في كل مكان','نسخ صوتية ترافق الطفل طوال اليوم.'],['موارد للاحتفاظ بها','أنشطة ومواد تعليمية قابلة للتنزيل.']], planTitle:'بسيط لكل العائلة', planName:'iFilino Kids Premium', monthly:'شهرياً', planNote:'يمكن الإلغاء في أي وقت. يشمل وصول العائلة.', included:['مكتبة Premium كاملة','القصص والتعلم والعلوم والطبيعة والفضاء والتكنولوجيا','الصوت والموارد القابلة للتنزيل','محتوى جديد بانتظام'], finalTitle:'المغامرة القادمة تبدأ هنا.', finalText:'افتح مساحة آمنة ينمو فيها الفضول كل يوم.' },
};
const BENEFIT_ICONS = [BookOpen, FlaskConical, Headphones, Download];
const WORLDS = [Rocket, Leaf, BookOpen, FlaskConical];
const CONVERSION_COPY = {
  fr: {
    hero:'Grandir, apprendre et rêver — ensemble.', intro:'Un espace calme et joyeux où chaque enfant explore à son rythme, et où les parents gardent l’esprit tranquille.', secondary:'Continuer gratuitement', reassurances:['Sans publicité','Annulation à tout moment','Pour toute la famille'],
    compareLabel:'Choisir simplement', compareTitle:'Gratuit ou Premium, à chaque famille son rythme', free:'Gratuit', premium:'Premium', discover:'Pour découvrir', familyChoice:'Le choix des familles', rows:[['Histoires et découvertes','Sélection gratuite','Accès illimité'],['Contenus audio','Aperçus','Bibliothèque complète'],['Activités et ressources','Sélection gratuite','Toutes les ressources'],['Récompenses exclusives','—','Incluses'],['Publicité','Aucune','Aucune']],
    proofLabel:'La parole aux familles', proofTitle:'Des petits moments qui comptent', testimonials:[['« Notre rituel du soir est devenu plus calme. Lina choisit une histoire et nous la lisons ensemble. »','Nadia, maman de Lina, 6 ans'],['« Les contenus de science répondent aux mille questions de mon fils, avec des mots adaptés. »','Youssef, papa d’Adam, 8 ans'],['« J’aime pouvoir proposer un écran utile, sans publicité et sans surstimulation. »','Sofia, maman de deux enfants']],
    guaranteeTitle:'Essayez en toute sérénité', guaranteeText:'Vous gardez le contrôle : abonnement annulable à tout moment, aucun engagement long terme et aucun contenu publicitaire.',
    faqLabel:'Questions fréquentes', faqTitle:'Tout ce que les parents veulent savoir', faqs:[['Puis-je continuer gratuitement ?','Oui. La sélection gratuite reste disponible pour découvrir iFilino Kids sans abonnement.'],['Combien d’enfants peuvent en profiter ?','L’offre est pensée pour la famille et permet à chaque enfant de progresser à son rythme.'],['Puis-je annuler facilement ?','Oui, à tout moment depuis votre espace. Votre accès reste actif jusqu’à la fin de la période en cours.'],['Les contenus sont-ils adaptés aux enfants ?','Les expériences sont claires, positives, adaptées au jeune public et sans publicité.'],['Que débloque Premium ?','Toute la bibliothèque, les audios, les ressources éducatives et les récompenses Premium exclusives.']], final:'Commencez gratuitement, puis passez à Premium seulement quand cela convient à votre famille.'
  },
  en: {
    hero:'Grow, learn and dream — together.', intro:'A calm and joyful space where every child explores at their own pace, while parents enjoy peace of mind.', secondary:'Continue for free', reassurances:['No ads','Cancel anytime','For the whole family'],
    compareLabel:'Choose simply', compareTitle:'Free or Premium, every family has its own pace', free:'Free', premium:'Premium', discover:'To discover', familyChoice:'Families’ choice', rows:[['Stories and discoveries','Free selection','Unlimited access'],['Audio content','Previews','Full library'],['Activities and resources','Free selection','All resources'],['Exclusive rewards','—','Included'],['Advertising','None','None']],
    proofLabel:'From our families', proofTitle:'Little moments that matter', testimonials:[['“Bedtime has become calmer. Lina picks a story and we read it together.”','Nadia, Lina’s mum, age 6'],['“The science content answers my son’s many questions in words he understands.”','Youssef, Adam’s dad, age 8'],['“I can offer useful screen time, without ads or overstimulation.”','Sofia, mum of two']],
    guaranteeTitle:'Try it with peace of mind', guaranteeText:'You stay in control: cancel anytime, no long-term commitment and no advertising.', faqLabel:'Frequently asked questions', faqTitle:'What parents want to know', faqs:[['Can I keep using it for free?','Yes. The free selection remains available without subscribing.'],['How many children can use it?','The plan is designed for families, letting every child progress at their own pace.'],['Can I cancel easily?','Yes, anytime from your account. Access continues until the end of the current period.'],['Is the content child-friendly?','Experiences are clear, positive, made for young audiences and ad-free.'],['What does Premium unlock?','The whole library, audio, learning resources and exclusive Premium rewards.']], final:'Start free, then choose Premium only when it feels right for your family.'
  },
  ar: {
    hero:'نكبر ونتعلم ونحلم — معاً.', intro:'مساحة هادئة ومبهجة يستكشف فيها كل طفل وفق وتيرته، ويطمئن فيها الآباء.', secondary:'المتابعة مجاناً', reassurances:['بدون إعلانات','إلغاء في أي وقت','لكل العائلة'],
    compareLabel:'اختيار بسيط', compareTitle:'مجاني أو Premium، لكل عائلة وتيرتها', free:'مجاني', premium:'Premium', discover:'للاكتشاف', familyChoice:'اختيار العائلات', rows:[['القصص والاكتشافات','مجموعة مجانية','وصول غير محدود'],['المحتوى الصوتي','معاينات','المكتبة كاملة'],['الأنشطة والموارد','مجموعة مجانية','كل الموارد'],['مكافآت حصرية','—','مشمولة'],['الإعلانات','لا يوجد','لا يوجد']],
    proofLabel:'من عائلاتنا', proofTitle:'لحظات صغيرة تصنع الفرق', testimonials:[['« أصبح وقت النوم أكثر هدوءاً. تختار لينا قصة ونقرأها معاً. »','نادية، والدة لينا، 6 سنوات'],['« محتوى العلوم يجيب عن أسئلة ابني الكثيرة بكلمات يفهمها. »','يوسف، والد آدم، 8 سنوات'],['« أحب أن أقدم وقت شاشة مفيداً، بلا إعلانات أو تحفيز مفرط. »','صوفيا، أم لطفلين']],
    guaranteeTitle:'جرّبوا بكل اطمئنان', guaranteeText:'أنتم من يتحكم: إلغاء في أي وقت، دون التزام طويل ودون إعلانات.', faqLabel:'الأسئلة الشائعة', faqTitle:'ما يريد الآباء معرفته', faqs:[['هل يمكنني المتابعة مجاناً؟','نعم، تبقى المجموعة المجانية متاحة دون اشتراك.'],['كم طفلاً يمكنه الاستفادة؟','العرض مصمم للعائلة ويسمح لكل طفل بالتقدم وفق وتيرته.'],['هل يمكنني الإلغاء بسهولة؟','نعم، في أي وقت من حسابك.'],['هل المحتوى مناسب للأطفال؟','التجارب واضحة وإيجابية ومصممة للصغار ودون إعلانات.'],['ماذا يفتح Premium؟','المكتبة كاملة والصوت والموارد التعليمية والمكافآت الحصرية.']], final:'ابدؤوا مجاناً، ثم اختاروا Premium حين يناسب عائلتكم.'
  },
};

export default function KidsPremiumPage() {
  const { language } = useKidsRouteLanguage();
  const copy = COPY[language] || COPY.en;
  const conversion = CONVERSION_COPY[language] || CONVERSION_COPY.en;
  const { subscribe: beginSubscription } = useSubscription();
  const startSubscription = () => beginSubscription({ plan: 'premium', billingCycle: 'monthly', language });
  const login = `/kids/${language}/login`;
  const freeLibrary = `/kids/${language}`;
  return <div className="portal portal-kids kids-premium-page" dir={language === 'ar' ? 'rtl' : 'ltr'}>
    <SeoHead title={`iFilino Kids Premium — ${copy.title}`} description={copy.intro} canonicalPath={`/kids/${language}/premium`} language={language} alternates={kidsAlternates('/premium')}/>
    <header className="portal-header"><div className="portal-shell portal-header-row"><PortalBrand portal="kids"/><span className="kids-premium-nav"><Crown/>{copy.nav}</span><Link className="portal-header-auth" to={login}>{copy.login}</Link></div></header>
    <main>
      <section className="kids-premium-hero"><div className="portal-shell kids-premium-hero__grid"><div className="kids-premium-hero__copy"><span className="kids-premium-eyebrow"><Sparkles/>{copy.eyebrow}</span><h1>{conversion.hero}</h1><p>{conversion.intro}</p><div className="kids-premium-actions"><button type="button" className="kids-premium-cta" onClick={startSubscription}><Crown/>{copy.cta}<ArrowRight/></button><Link to={freeLibrary} className="kids-premium-secondary">{conversion.secondary}</Link></div><span className="kids-premium-trust"><ShieldCheck/>{copy.trusted}</span><ul className="kids-premium-reassurance">{conversion.reassurances.map(item=><li key={item}><Check/>{item}</li>)}</ul></div><div className="kids-premium-visual" role="img" aria-label={copy.benefitsTitle}><span className="kids-premium-family"><UsersRound/><i><Heart/></i></span><div className="kids-premium-visual__core"><Crown/></div>{WORLDS.map((Icon,index)=><span key={index} className={`kids-premium-world world-${index}`}><Icon/></span>)}<span className="kids-premium-star star-one"><Star/></span><span className="kids-premium-star star-two"><Sparkles/></span></div></div></section>
      <section id="avantages" className="portal-shell kids-premium-benefits" aria-labelledby="benefits-title"><div className="kids-premium-section-head"><span>Premium</span><h2 id="benefits-title">{copy.benefitsTitle}</h2></div><div className="kids-premium-benefit-grid">{copy.benefits.map(([title,text],index)=>{const Icon=BENEFIT_ICONS[index];return <article key={title}><span><Icon/></span><h3>{title}</h3><p>{text}</p></article>})}</div></section>
      <section className="kids-premium-compare-section" aria-labelledby="compare-title"><div className="portal-shell"><div className="kids-premium-section-head"><span>{conversion.compareLabel}</span><h2 id="compare-title">{conversion.compareTitle}</h2></div><div className="kids-premium-comparison" role="table" aria-label={conversion.compareTitle}><div className="kids-premium-comparison__head" role="row"><span role="columnheader"/><div role="columnheader"><strong>{conversion.free}</strong><small>{conversion.discover}</small></div><div className="is-premium" role="columnheader"><small><Crown/>{conversion.familyChoice}</small><strong>{conversion.premium}</strong></div></div>{conversion.rows.map(([label,free,premium])=><div className="kids-premium-comparison__row" role="row" key={label}><strong role="rowheader">{label}</strong><span role="cell">{free==='—'?<X/>:<Check/>}{free}</span><span role="cell"><Check/>{premium}</span></div>)}</div></div></section>
      <section className="kids-premium-plan-section"><div className="portal-shell kids-premium-plan-grid"><div className="kids-premium-plan-copy"><span className="kids-premium-eyebrow"><ShieldCheck/>{copy.planTitle}</span><h2>{copy.planName}</h2><ul>{copy.included.map(item=><li key={item}><Check/><span>{item}</span></li>)}</ul></div><article className="kids-premium-plan-card"><div className="kids-premium-plan-card__top"><Crown/><strong>{copy.planName}</strong><span>Populaire</span></div><div className="kids-premium-price"><strong>4,99 €</strong><span>{copy.monthly}</span></div><p>{copy.planNote}</p><button type="button" className="kids-premium-cta" onClick={startSubscription}>{copy.cta}<ArrowRight/></button></article></div></section>
      <section className="portal-shell kids-premium-proof" aria-labelledby="proof-title"><div className="kids-premium-section-head"><span>{conversion.proofLabel}</span><h2 id="proof-title">{conversion.proofTitle}</h2></div><div className="kids-premium-testimonials">{conversion.testimonials.map(([quote,author])=><figure key={author}><div aria-label="5 étoiles">{[1,2,3,4,5].map(n=><Star key={n}/>)}</div><blockquote>{quote}</blockquote><figcaption><span><UsersRound/></span>{author}</figcaption></figure>)}</div></section>
      <section className="portal-shell kids-premium-guarantee"><span><ShieldCheck/></span><div><h2>{conversion.guaranteeTitle}</h2><p>{conversion.guaranteeText}</p></div><BadgeCheck/></section>
      <section className="portal-shell kids-premium-faq" aria-labelledby="faq-title"><div className="kids-premium-section-head"><span>{conversion.faqLabel}</span><h2 id="faq-title">{conversion.faqTitle}</h2></div><div>{conversion.faqs.map(([question,answer],index)=><details key={question} open={index===0}><summary>{question}<ChevronDown/></summary><p>{answer}</p></details>)}</div></section>
      <section className="portal-shell kids-premium-final"><div><Sparkles/><h2>{copy.finalTitle}</h2><p>{conversion.final}</p><span className="kids-premium-final__trust"><LockKeyhole/>{conversion.reassurances.join(' · ')}</span></div><div className="kids-premium-final__actions"><button type="button" className="kids-premium-cta" onClick={startSubscription}><Crown/>{copy.cta}<ArrowRight/></button><Link to={freeLibrary}>{conversion.secondary}</Link></div></section>
    </main><PortalFooter portal="kids" language={language}/>
  </div>;
}
