'use strict';
const express=require('express');const path=require('path');const fs=require('fs');const crypto=require('crypto');const AdmZip=require('adm-zip');const sharp=require('sharp');const {QueryTypes}=require('sequelize');const {sequelize}=require('../../../models');const {requireAuth,requireRole}=require('../../../middleware/auth');
const {ManifestValidator}=require('./importer/ManifestValidator');const PackageExtractor=require('./importer/PackageExtractor');const {VersionManager}=require('./importer/VersionManager');const ImportLogger=require('./importer/ImportLogger');const SeriesResolver=require('./importer/SeriesResolver');const EpisodeResolver=require('./importer/EpisodeResolver');const MetadataImporter=require('./importer/MetadataImporter');const AssetImporter=require('./importer/AssetImporter');const PageImporter=require('./importer/PageImporter');
const router=express.Router();const guard=[requireAuth,requireRole(['superadmin'])];const ah=fn=>(req,res,next)=>Promise.resolve(fn(req,res,next)).catch(next);
const slugify=value=>String(value||'comic').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,170)||'comic';
router.post('/admin/imports/:id/create-draft',...guard,ah(async(req,res,next)=>{
 const jobs=await sequelize.query('SELECT * FROM comic_import_jobs WHERE id=:id LIMIT 1',{replacements:{id:req.params.id},type:QueryTypes.SELECT}),job=jobs[0];if(!job)return res.status(404).json({error:'Import not found'});if(Number(job.package_version||0)<2)return next('route');if(job.status!=='ready_for_review')return res.status(409).json({error:'Only a validated package can create or update an episode.'});
 const logger=new ImportLogger(),{entries,manifest:raw}=PackageExtractor.inspect(job.stored_path),manifest=ManifestValidator.validate(raw);logger.add('ZIP extracted.').add('Manifest detected.',{seriesId:manifest.seriesId,episodeId:manifest.episodeId});
 const tx=await sequelize.transaction();let stage=null,finalDir=null,backup=null;
 try{
  let series=await SeriesResolver.find(sequelize,manifest.seriesId,tx),seriesCreated=false;if(!series){series=await SeriesResolver.create(sequelize,manifest,req.user.id,tx);seriesCreated=true;logger.add('New series created.',{seriesId:manifest.seriesId})}else logger.add('Series found.',{seriesId:manifest.seriesId});
  let episode=await EpisodeResolver.find(sequelize,manifest.episodeId,tx);if(episode&&Number(episode.series_id)!==Number(series.id)){const e=new Error('episodeId belongs to another series.');e.status=409;throw e}const action=VersionManager.action(episode?episode.episode_version:null,manifest.episodeVersion);logger.add(episode?'Existing episode detected.':'New episode detected.',{episodeId:manifest.episodeId,storedVersion:episode?.episode_version||null,importedVersion:manifest.episodeVersion,action});
  const root=path.join(__dirname,'../../../uploads/comics/series'),stageRoot=path.join(root,'.staging');fs.mkdirSync(stageRoot,{recursive:true});stage=path.join(stageRoot,job.id);fs.rmSync(stage,{recursive:true,force:true});fs.mkdirSync(stage,{recursive:true});
  const pages=await PageImporter.copy(entries,manifest,stage),assets=AssetImporter.copy(entries,AssetImporter.references(manifest),stage);let coverName=pages[0].name;const coverRef=manifest.coverImage||manifest.cover||manifest.coverFile;if(coverRef){const entry=AssetImporter.entry(entries,coverRef);if(!entry){const e=new Error(`Asset missing: ${coverRef}`);e.status=422;throw e}coverName=`cover${path.extname(entry.entryName).toLowerCase()}`;fs.writeFileSync(path.join(stage,coverName),entry.getData())}
  const publicBase=`/uploads/comics/series/${manifest.seriesId}/${manifest.episodeId}`,meta=MetadataImporter.episode(manifest,{valid:true,pageCount:pages.length,assets},`${publicBase}/${coverName}`);
  if(action==='create'){const [episodeId]=await sequelize.query(`INSERT INTO comic_episodes (series_id,episode_uid,number,slug,title,status,language,page_count,reading_modes,episode_version,publication_order,cover_image,package_metadata,validation_report,created_at,updated_at) VALUES (:seriesId,:uid,:number,:slug,:title,'draft',:language,:count,:modes,:version,:ordering,:cover,:metadata,:report,NOW(),NOW())`,{replacements:{seriesId:series.id,uid:manifest.episodeId,number:meta.number,slug:meta.slug,title:meta.title,language:meta.language,count:pages.length,modes:meta.modes,version:meta.version,ordering:meta.order,cover:meta.cover,metadata:meta.metadata,report:meta.report},transaction:tx,type:QueryTypes.INSERT});episode={id:episodeId};}
  else{await sequelize.query(`UPDATE comic_episodes SET number=:number,title=:title,language=:language,page_count=:count,reading_modes=:modes,episode_version=:version,publication_order=:ordering,cover_image=:cover,package_metadata=:metadata,validation_report=:report,status='draft',updated_at=NOW() WHERE id=:id`,{replacements:{id:episode.id,number:meta.number,title:meta.title,language:meta.language,count:pages.length,modes:meta.modes,version:meta.version,ordering:meta.order,cover:meta.cover,metadata:meta.metadata,report:meta.report},transaction:tx});await sequelize.query('DELETE FROM comic_pages WHERE episode_id=:id',{replacements:{id:episode.id},transaction:tx});}
  for(let i=0;i<pages.length;i++){const p=pages[i];await sequelize.query('INSERT INTO comic_pages (episode_id,page_number,image_url,width,height,bytes,checksum,created_at,updated_at) VALUES (:episodeId,:number,:url,:width,:height,:bytes,:checksum,NOW(),NOW())',{replacements:{episodeId:episode.id,number:i+1,url:`${publicBase}/${p.name}`,width:p.width,height:p.height,bytes:p.bytes,checksum:p.checksum},transaction:tx})}
  await sequelize.query('UPDATE comic_series SET title=:title,language=:language,season_number=:season,cover_url=COALESCE(cover_url,:cover),banner_url=COALESCE(banner_url,:banner),genres=COALESCE(:genres,genres),tags=COALESCE(:tags,tags),package_metadata=:metadata,updated_at=NOW() WHERE id=:id',{replacements:{id:series.id,title:manifest.seriesTitle,language:manifest.language,season:manifest.seasonNumber,cover:`${publicBase}/${coverName}`,banner:`${publicBase}/${pages[0].name}`,genres:(manifest.genres||manifest.categories)?JSON.stringify(manifest.genres||manifest.categories):null,tags:manifest.tags?JSON.stringify(manifest.tags):null,metadata:JSON.stringify({publisher:manifest.publisher||null,generatedAt:manifest.generatedAt})},transaction:tx});
  finalDir=path.join(root,manifest.seriesId,manifest.episodeId);fs.mkdirSync(path.dirname(finalDir),{recursive:true});if(fs.existsSync(finalDir)){backup=`${finalDir}.backup-${job.id}`;fs.rmSync(backup,{recursive:true,force:true});fs.renameSync(finalDir,backup)}fs.renameSync(stage,finalDir);stage=null;logger.add('Pages imported.',{count:pages.length}).add('Assets imported.',{count:assets.length}).add('Database updated.');
  const summary={...(typeof job.summary==='string'?JSON.parse(job.summary):job.summary||{}),seriesId:series.id,episodeId:episode.id,seriesUid:manifest.seriesId,episodeUid:manifest.episodeId,episodeVersion:manifest.episodeVersion,pageCount:pages.length,action,draftCreated:true};logger.add('Import completed.');
  await sequelize.query("UPDATE comic_import_jobs SET status='imported',summary=:summary,import_log=:log,updated_at=NOW() WHERE id=:id",{replacements:{id:job.id,summary:JSON.stringify(summary),log:JSON.stringify(logger.json())},transaction:tx});await tx.commit();if(backup)fs.rmSync(backup,{recursive:true,force:true});
  return res.status(action==='create'?201:200).json({ok:true,action,seriesId:series.id,episodeId:episode.id,seriesUid:manifest.seriesId,episodeUid:manifest.episodeId,episodeVersion:manifest.episodeVersion,pageCount:pages.length,status:'draft',log:logger.json()});
 }catch(error){await tx.rollback();if(stage)fs.rmSync(stage,{recursive:true,force:true});if(finalDir&&backup&&fs.existsSync(backup)){fs.rmSync(finalDir,{recursive:true,force:true});fs.renameSync(backup,finalDir)}throw error}
}));

router.post('/admin/imports/:id/create-draft',...guard,ah(async(req,res)=>{const rows=await sequelize.query('SELECT * FROM comic_import_jobs WHERE id=:id LIMIT 1',{replacements:{id:req.params.id},type:QueryTypes.SELECT});const job=rows[0];if(!job)return res.status(404).json({error:'Import not found'});const old=typeof job.summary==='string'?JSON.parse(job.summary):job.summary||{};if(job.status==='imported')return res.json({ok:true,alreadyCreated:true,seriesId:old.seriesId||null,episodeId:old.episodeId||null,slug:old.slug||null,status:'draft'});if(job.status!=='ready_for_review')return res.status(409).json({error:'Only a validated package can create a draft.'});if(job.source_type!=='ifilino_zip')return res.status(422).json({error:'PDF draft extraction is not available yet.'});
  const entries=new AdmZip(job.stored_path).getEntries().filter(e=>!e.isDirectory);const metaEntry=entries.find(e=>/(^|\/)(manifest|metadata|series)\.json$/i.test(e.entryName));let meta={};if(metaEntry){try{meta=JSON.parse(metaEntry.getData().toString('utf8'))}catch{return res.status(422).json({error:`Invalid metadata: ${metaEntry.entryName}`})}}const pageEntries=entries.filter(e=>/(^|\/)page-\d+\.(png|jpe?g|webp)$/i.test(e.entryName)).sort((a,b)=>a.entryName.localeCompare(b.entryName,undefined,{numeric:true}));if(!pageEntries.length)return res.status(422).json({error:'No page-001 images found.'});const cover=entries.find(e=>/(^|\/)(front-cover|cover)\.(png|jpe?g|webp)$/i.test(e.entryName))||pageEntries[0];const title=meta.title||meta.series?.title||path.basename(job.original_name,path.extname(job.original_name)).replace(/[-_]+/g,' ');let slug=slugify(meta.slug||title);const exists=await sequelize.query('SELECT id FROM comic_series WHERE slug=:slug',{replacements:{slug},type:QueryTypes.SELECT});if(exists.length)slug+=`-${Date.now().toString(36)}`;const dir=path.join(__dirname,'../../../uploads/comics/series',slug,'episode-1');fs.mkdirSync(dir,{recursive:true});const save=(e,n)=>{const target=path.join(dir,n);fs.writeFileSync(target,e.getData());return target};const coverExt=path.extname(cover.entryName).toLowerCase();save(cover,`cover${coverExt}`);const pages=[];for(let i=0;i<pageEntries.length;i++){const ext=path.extname(pageEntries[i].entryName).toLowerCase();const name=`page-${String(i+1).padStart(3,'0')}${ext}`;const file=save(pageEntries[i],name);const info=await sharp(file).metadata();const data=fs.readFileSync(file);pages.push({name,width:info.width||null,height:info.height||null,bytes:data.length,checksum:crypto.createHash('sha256').update(data).digest('hex')})}
  const tx=await sequelize.transaction();try{const [seriesId]=await sequelize.query(`INSERT INTO comic_series (owner_user_id,slug,title,subtitle,synopsis,cover_url,banner_url,language,age_rating,status,genres,tags,created_at,updated_at) VALUES (:owner,:slug,:title,:subtitle,:synopsis,:cover,:banner,:language,:age,'draft',:genres,:tags,NOW(),NOW())`,{replacements:{owner:req.user.id,slug,title,subtitle:meta.subtitle||null,synopsis:meta.synopsis||meta.description||null,cover:`/uploads/comics/series/${slug}/episode-1/cover${coverExt}`,banner:`/uploads/comics/series/${slug}/episode-1/${pages[0].name}`,language:meta.language||'en',age:meta.age_rating||'13+',genres:JSON.stringify(meta.genres||[]),tags:JSON.stringify(meta.tags||[])},transaction:tx,type:QueryTypes.INSERT});const [episodeId]=await sequelize.query(`INSERT INTO comic_episodes (series_id,number,slug,title,status,language,page_count,reading_modes,created_at,updated_at) VALUES (:seriesId,1,'episode-1',:title,'draft',:language,:count,'["classic","vertical"]',NOW(),NOW())`,{replacements:{seriesId,title:meta.episode?.title||'Episode 1',language:meta.language||'en',count:pages.length},transaction:tx,type:QueryTypes.INSERT});for(let i=0;i<pages.length;i++){const p=pages[i];await sequelize.query(`INSERT INTO comic_pages (episode_id,page_number,image_url,width,height,bytes,checksum,created_at,updated_at) VALUES (:episodeId,:number,:url,:width,:height,:bytes,:checksum,NOW(),NOW())`,{replacements:{episodeId,number:i+1,url:`/uploads/comics/series/${slug}/episode-1/${p.name}`,...p},transaction:tx,type:QueryTypes.INSERT})}const summary={...old,seriesId,episodeId,slug,pageCount:pages.length,draftCreated:true,automaticPublication:false};await sequelize.query("UPDATE comic_import_jobs SET status='imported',summary=:summary,updated_at=NOW() WHERE id=:id",{replacements:{id:job.id,summary:JSON.stringify(summary)},transaction:tx});await tx.commit();return res.status(201).json({ok:true,seriesId,episodeId,slug,pageCount:pages.length,status:'draft'})}catch(error){await tx.rollback();fs.rmSync(path.join(__dirname,'../../../uploads/comics/series',slug),{recursive:true,force:true});throw error}}));
module.exports=router;
